### ISSUE TITLE
[Feature Request] Hope for websocket demo

### ISSUE THREAD

**Issue by DavexPro** [swooletw/laravel-swoole#144]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP Info:

```
PHP 7.2.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Aug 19 2018 07:16:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.9-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

Swoole Info:

```
swoole

swoole support => enabled
Version => 4.1.2
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
debug => enabled
trace-log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

2. Please provide your Laravel/Lumen version.

`"laravel/framework": "5.5.*"`

3. Which release version of this package are you using?

`"swooletw/laravel-swoole": "^2.4"`

4. What did you do? If possible, provide a recipe for reproducing the error.

I am confused how to use websocket base on this package. I use the `nginx` config from the wiki, but it seems something wrong.

If possible, would you mind giving some examples about using websocket including nginx.

```
    location @swoole {
        set $suffix "";

        if ($uri = /index.php) {
            set $suffix "/";
        }

        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        # IF https
        # proxy_set_header HTTPS "on";

        proxy_pass http://127.0.0.1:1215$suffix;
    }
```
Any wrong?

5. What did you expect to see?

Expect to run a easy demo of websocket.

6. What did you see instead?

```
./wscat --connect ws://my-domain.com/
error: Unexpected server response: 200
>
```

**Comment by albertcht** [comment]
Hi @DavexPro ,

I think [websocket wiki](https://github.com/swooletw/laravel-swoole/wiki/7.-Websocket) has covered  most of the websocket usages provided by this package. If you have experience with websocket and `socket.io` development, it should not be difficult to understand.

I will consider to create another repo for websocket demo if I have free time, but I think I will still focus on `coroutine feature` in the short run.

**Comment by DavexPro** [comment]
I find something bizarre that I can communicate with swoole right without nginx, but when I communicate with swoole by nginx it will happen. I check for the nginx config twice, it is identical. Would you mind telling me how you deploy your application using websocket with nginx? BTW, the http service is totally fine.

**Comment by Sravan2** [comment]
I have successfully installed laravel and swoole package
But the issue is how to use websocket(socket.io) to emit from websocket.php(route file)
Please have a demo on how to use websocket for me this is an high priority

Here are my swoole and laravel details

+-----------------+---------------------------------------------------------------+
| Name            | Value                                                         |
+-----------------+---------------------------------------------------------------+
| PHP Version     | 7.2.9-1+ubuntu16.04.1+deb.sury.org+1                          |
| Swoole Version  | 4.2.1                                                         |
| Laravel Version | 5.2.45                                                        |
| Listen IP       | 127.0.0.1                                                     |
| Listen Port     | 1215                                                          |
| Server Status   | Online                                                        |
| Reactor Num     | 2                                                             |
| Worker Num      | 2                                                             |
| Task Worker Num | 0                                                             |
| Websocket Mode  | Off                                                           |
| PID             | 12784                                                         |
| Log Path        | /var/www/html/laravel_5.2_swoole/storage/logs/swoole_http.log |
+-----------------+---------------------------------------------------------------+
