### ISSUE TITLE
Question about workers & sandbox operation

### ISSUE THREAD

**Issue by netdown** [swooletw/laravel-swoole#354]
Hi,
I know that this is not an issue, but I am afraid this is the only place I can get information. Please clarify the following, may be a good idea to also detail this in the documentation.

I roughly understand the concept of workers and sandbox. However, it is unclear for me that how exactly Laravel exists in these workers, how do they share the traffic. I have read that these workers do not share data, however, the sandbox container is required to avoid unexpected behavior. This means that there are a given number of workers which do not know about each other, but each serves many clients and these clients' data would mix up without sandbox? Moreover, the pre resolved instances are resolved one time for each worker, not once totally? 

Let me explain my specific problem. I am working with websockets, some events (actions) which the client triggers may (not everytime) require a confirmation. In this case, I would like to store a callable at server side, which executes the complete action after confirmation is received. So among others, there would be no need to send the data again. Clearly, the question is data sharing. As I cannot store a callable in Swoole Table, I thought of using a pre resolved class, which may not be possible if the above is correct - but I'm not sure. 

Thanks and in advance.

**Comment by albertcht** [comment]
Hi @netdown ,

Laravel instance exists in each worker, and a worker is a process. That's why they can't share the data unless you use shared memory or other storage. There's a worker manager in front of those workers. You can think it of FPM in traditional PHP.

The sandbox container is to avoid dirty bindings in previous requests. Because some bindings are declared as singletons in app container, they will pollute the container bindings. So the sandbox will clean those bindings except pre-resolved instances (some stateless instances) to make sure the container is clean in every request. Pre-resolved instances will be resolved only once before handling any requests.

In your case, you just need to record your confirmation state not matter in Swoole table or database.
