### ISSUE TITLE
Redis connection become a zombie after using Cache class

### ISSUE THREAD

**Issue by abdulnewswav** [swooletw/laravel-swoole#365]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.3.13 (cli)
Swoole 4.4.14

2. Please provide your Laravel/Lumen version.

Lumen 5.7 and 5.8

3. Which release version of this package are you using?
2.6

4. What did you do? If possible, provide a recipe for reproducing the error.
Call any api that use Cache::xxx, driver should be redis, predis in my case
illuminate/redis
predis:1.1.1

5. What did you expect to see?
redis connection get close after api call, or having pool of  redis connections

6. What did you see instead?
I see X redis connection still established and opened after having X api calls uses Cache class

**Comment by abdulnewswav** [comment]
Oh is not just about Redis Connection, also HTTP connections from Guzzle will become zombie connections

**Comment by codercms** [comment]
@abdulnewswav No, it is not a zombie connections, it is one of a long-running (long-live) application's advantages. Establishing redis/database connection on each request will slow down your application. When your app is started and used database or cache methods, connection will be established at once and application will reuse it for all next requests.
If you want to manully close a connections after each request you can use middleware for this case - https://laravel.com/docs/6.x/middleware#terminable-middleware. You can close database connection for example by calling DB::connection('your_connection_name')->disconnect();

**Comment by abdulnewswav** [comment]
@codercms I don't think is working in this way, after I made some debugging I noticed that for every request it will create new socket connection to Redis server, until Redis server get it max of allowed connections 
I hope it was using a pool of connections, but that would be a bit hard, also this lib doesn't support mysql connections pool yet 
The only options I got is to create my own sub class of Cache class and add a destructor to close Redis connection and making that object reset for every request

**Comment by codercms** [comment]
@abdulnewswav i think there is some mistake in your application code.
Just tested my app (12 workers) with AB with concurrency about 1000.
And i checked my connections list during testing (redis-cli SHOW CLIENTS), it shown exactly 12 connections + 1 (my connection to redis-cli).
Do you have in your swoole_http.php config file following lines in the pre_resolved section?
```php
        'cache',
        'cache.store',
```

And check please instances and providers sections, maybe you're resetting cache on every request.

**Comment by codercms** [comment]
@abdulnewswav about connection pool. You don't actually need connection pool if you're using synchronous database driver, because it blocks the entire thread in a worker process. However this package has something to use Coroutine-based MySQL client - https://github.com/swooletw/laravel-swoole/blob/master/src/HttpServiceProvider.php#L215, but i'm not sure how does it work with concurrent coroutines. I can't find any code that prevents connection usage by another concurrent coroutine while first coroutine is still in transaction.

But you can implement your own connection pool. By the way, i found the better performance with only 1 connection in the pool, but with increased workers number. But in your app results may be diffrent.
I implemented my own CP here - https://github.com/codercms/laravel-pg-conn-pool
You can do simmilar thing for your app.

P.S. You don't need to compile "special" pdo extension for PHP, if you're not using Postgres. pdo_mysql can be hooked by Swoole at runtime.
```
Swoole\Runtime::enableCoroutine(); // this will prevent pdo_mysql from blocking your worker thread
```

Read more here:
* https://github.com/swoole/swoole-src#-amazing-runtime-hooks
* https://wiki.swoole.com/wiki/page/p-runtime.html
