### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by hakuno** [swooletw/laravel-swoole#66]
Good job. It's great. I wanna check it out as soon.

By the way... do you have any other benchmarking report?

Because I care about memory leaks as [PHP-PM](https://github.com/php-pm/php-pm) also has.

What's the memory leak rate? Does it have any?

**Comment by albertcht** [comment]
Hi @hakuno ,

1. Please read [Readme](https://github.com/swooletw/laravel-swoole#benchmark) for the basic benchmark result.
2. Potential memory leak might still exist in Swoole. This reason is still unknown, but there's a `max_request` config in Swoole for solving this problem. Each worker will restart gracefully after handling the number of `max_request` to prevent memory leak.

**Comment by hakuno** [comment]
All right. Thanks for reply, @albertcht
