### ISSUE TITLE
predis dependency 

### ISSUE THREAD

**Issue by ctf0** [swooletw/laravel-swoole#68]
not everyone is using that client, so it might be a good idea to rely instead on whatever client the project is using `phpredis` or `predis`.

there is also redis-async by swoole, maybe the package could rely on it instead if it proves to be better ?

**Comment by albertcht** [comment]
Hi @ctf0 ,

1. `presdis/predis` is required by Laravel by default.
2. `predis/predis` is required by this package because it's one of the room drivers for websocket.
3. Async clients will be hard to be applied on traditional synchronous framework like Laraval. Coroutine clients are in progress in another branch. Coroutine client for Redis will be considered to be supported in the future.

**Comment by ctf0** [comment]
> `presdis/predis` is required by Laravel by default.

nop https://laravel.com/docs/5.5/redis#introduction

> `predis/predis` is required by this package because it's one of the room drivers for websocket.

cant the `phpredis` do the same ?

> Coroutine client for Redis will be considered to be supported in the future.

awesome 👍

**Comment by albertcht** [comment]
> nop https://laravel.com/docs/5.5/redis#introduction

This is interesting. `predis/predis` is required by `laravel/framework` ([see here](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Redis/composer.json#L20)) by default. You can try to new a laravel project to see if it will install `predis/predis`.

> cant the phpredis do the same ?

Yes, but users will need to install another extension for `phpredis`.

**Comment by ctf0** [comment]
WOT,  am not sure why its being pre-installed specially that the user has the option to use another 🙄

**Comment by shenglin-php** [comment]
Predis has been abandoned by the author. Laravel 6 recommends phpredis now
